### ISSUE TITLE
Reference of code

### ISSUE THREAD

**Issue by yoshitomo-matsubara** [shaoshitong/CCD#1]
Hi @shaoshitong

Congratulation for the acceptance of your paper at ACCV 2022!

I happened to find this repository and noticed that some of the code came from torchdistill.

e.g.,
- CRD ([this repo](https://github.com/shaoshitong/CCD/commit/e08ed595d15c771ac22ba743a3f01b6a6c06e039) vs. [torchdistill](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/torchdistill/losses/single.py#L472-L643))
- KD ([this repo](https://github.com/shaoshitong/CCD/commit/037384691e3e86552c914df35f8350bc6a605952) vs. [torchdistill](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/torchdistill/losses/single.py#L87-L106))
- SPKD ([this repo](https://github.com/shaoshitong/CCD/blob/17aa096f8857db4823e510860b4d7d920bc40179/losses/SPKD.py) vs. [torchdistill](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/torchdistill/losses/single.py#L443-L468))
- SSKD ([this repo](https://github.com/shaoshitong/CCD/blob/fd9f18f3ca687ddaaf11c900493c9e3d96300ea6/losses/SSKD.py) vs. [torchdistill](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/torchdistill/losses/single.py#L677-L775))

Could you please update README with reference of code?

**Comment by shaoshitong** [comment]
> Hi @shaoshitong
> 
> Congratulation for the acceptance of your paper at ACCV 2022!
> 
> I happened to find this repository and noticed that some of the code came from torchdistill.
> 
> e.g.,
> 
> * CRD ([this repo](https://github.com/shaoshitong/CCD/commit/e08ed595d15c771ac22ba743a3f01b6a6c06e039) vs. [torchdistill](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/torchdistill/losses/single.py#L472-L643))
> * KD ([this repo](https://github.com/shaoshitong/CCD/commit/037384691e3e86552c914df35f8350bc6a605952) vs. [torchdistill](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/torchdistill/losses/single.py#L87-L106))
> * SPKD ([this repo](https://github.com/shaoshitong/CCD/blob/17aa096f8857db4823e510860b4d7d920bc40179/losses/SPKD.py) vs. [torchdistill](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/torchdistill/losses/single.py#L443-L468))
> * SSKD ([this repo](https://github.com/shaoshitong/CCD/blob/fd9f18f3ca687ddaaf11c900493c9e3d96300ea6/losses/SSKD.py) vs. [torchdistill](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/torchdistill/losses/single.py#L677-L775))
> 
> Could you please update README with reference of code?

Of course, the other day some busy forgot to reply, I will update immediately.

**Comment by yoshitomo-matsubara** [comment]
Thanks @shaoshitong !
